sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t wenbo0925/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true wenbo0925/react-test npm run test 

after_success:
    - docker build -t wenbo0925/multi-client ./client
    - docker build -t wenbo0925/multi-nginx ./nginx
    - docker build -t wenbo0925/multi-server ./server
    - docker build -t wenbo0925/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push wenbo0925/multi-client
    - docker push wenbo0925/multi-nginx
    - docker push wenbo0925/multi-server
    - docker push wenbo0925/multi-worker

deploy:  
    edge: true
    provider: elasticbeanstalk
    region: ca-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ca-central-1-562819747386
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
